### ISSUE TITLE
Allow recursion within types

### ISSUE THREAD

**Issue by alexyuly** [compostsoftware/compost#23]
Currently, no recursion (AKA cycles) within any types or component children is allowed. While we should continue to prohibit recursion within component children, we should allow recursion within types, because this is often useful and could be implemented.

For example, I want to define a complex type for a virtual DOM element, like so:

Element.yml:
```yaml
complex:
  type: string
  attributes: complex
  children: Children
```

Children.yml:
```yaml
list:
  - Element
  - string
  - number
```
